#!/bin/bash

MACLAB=/home/emscheffel/repositories/pymaclab
LD_LIBRARY_PATH=/home/emscheffel/repositories/pymaclab/libs
export MACLAB
export LD_LIBRARY_PATH

cd /home/emscheffel/repositories/pymaclab
clear
ipython -pylab -wthread
