function a0best=estnonreca(sigma,numtries,mkmatrix,mkstart,varargin);
%Estnonreca Estimates of Non-Recursive A0 matrix
%a0best=estnonreca(sigma,numtries,mkmatrix,mkstart,p1,p2,...);
% Using Random Starting values generated by a mkstart attempts to
% maximize the likelihood function for the A0 matrix. Numtries attempts are made
% to maximize the LLF. The result with the highest likelihood function is returned. 
% Note this procedure does not guarantee uniqueness of the A0 matrix.
%Definition of variables
%SIGMA variance covariance matrix
%NUMTRIES is how many times to attemp to estimate the system. 
%MKMATRIX is a user supplied procedure that generates the matrix A0 from a vector x
%MKSTART is a user supplied procedure that generates starting values that satisfy the 
%constraints on A0. 
% P1 P2 etc Arguments supplied after mkstart are parameters for mkstart.

disp(['Using the file ' mkmatrix ' to construct the A0 matrix'])
disp(['Using the file ' mkstart ' to generate starting values'])


avec=feval(mkstart,varargin{:}); 
resllf=zeros(numtries,1+length(avec));
for zr=1:numtries;
   disp(['Estimation Trial ' num2str(zr) ' out of ' num2str(numtries)])

   avec=feval(mkstart,varargin{:}); 
   x=constr('llfazero',avec,[],[],[],[],sigma,mkmatrix);
   resllf(zr,:)= [llfazero(x,sigma,mkmatrix) x'];
end;
srtres=sortrows(resllf,1);
a0best=feval(mkmatrix,srtres(1,2:27)');
